openapi: 3.0.0
info:
  version: '2014-11-12'
  x-release: v4
  title: 'AWS Config #X Amz Target=StarlingDoveService.BatchGetAggregateResourceConfig #X Amz Target=StarlingDoveService.BatchGetAggregateResourceConfig #X Amz Target=StarlingDoveService.PutRemediationConfigurations API'
  description: <fullname>Config</fullname> <p>Config provides a way to keep track of the configurations of all the Amazon Web Services resources associated with your Amazon Web Services account. You can use Config to get the current and historical configurations of each Amazon Web Services resource and also to get information about the relationship between the resources. An Amazon Web Services resource can be an Amazon Compute Cloud (Amazon EC2) instance, an Elastic Block Store (EBS) volume, an elastic network Interface (ENI), or a security group. For a complete list of resources currently supported by Config, see <a href="https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html#supported-resources">Supported Amazon Web Services resources</a>.</p> <p>You can access and manage Config through the Amazon Web Services Management Console, the Amazon Web Services Command Line Interface (Amazon Web Services CLI), the Config API, or the Amazon Web Services SDKs for Config. This reference guide contains documentation for the Config API and the Amazon Web Services CLI commands that you can use to manage Config. The Config API uses the Signature Version 4 protocol for signing requests. For more information about how to sign a request with this protocol, see <a href="https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html">Signature Version 4 Signing Process</a>. For detailed information about Config features and their associated actions or commands, as well as how to work with Amazon Web Services Management Console, see <a href="https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html">What Is Config</a> in the <i>Config Developer Guide</i>.</p>
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: config
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/config-2014-11-12.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://config.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Config Service multi-region endpoint
- url: https://config.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Config Service multi-region endpoint
- url: http://config.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Config Service endpoint for China (Beijing) and China (Ningxia)
- url: https://config.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Config Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=StarlingDoveService.PutRemediationConfigurations'
paths:
  /#X-Amz-Target=StarlingDoveService.PutRemediationConfigurations:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: PutRemediationConfigurations
      description: <p>Adds or updates the remediation configuration with a specific Config rule with the selected target or action. The API creates the <code>RemediationConfiguration</code> object for the Config rule. The Config rule must already exist for you to add a remediation configuration. The target (SSM document) must exist and have permissions to use the target. </p> <note> <p>If you make backward incompatible changes to the SSM document, you must call this again to ensure the remediations can run.</p> <p>This API does not support adding remediation configurations for service-linked Config Rules such as Organization Config rules, the rules deployed by conformance packs, and rules deployed by Amazon Web Services Security Hub.</p> </note> <note> <p>For manual remediation configuration, you need to provide a value for <code>automationAssumeRole</code> or use a value in the <code>assumeRole</code>field to remediate your resources. The SSM automation document can use either as long as it maps to a valid parameter.</p> <p>However, for automatic remediation configuration, the only valid <code>assumeRole</code> field value is <code>AutomationAssumeRole</code> and you need to provide a value for <code>AutomationAssumeRole</code> to remediate your resources.</p> </note>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutRemediationConfigurationsResponse'
              examples:
                PutRemediationConfigurations200Example:
                  summary: Default PutRemediationConfigurations 200
                  x-microcks-default: true
                  value:
                    FailedBatches: example
        '480':
          description: InsufficientPermissionsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsufficientPermissionsException'
              examples:
                PutRemediationConfigurations480Example:
                  summary: Default PutRemediationConfigurations 480
                  x-microcks-default: true
                  value: example
        '481':
          description: InvalidParameterValueException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterValueException'
              examples:
                PutRemediationConfigurations481Example:
                  summary: Default PutRemediationConfigurations 481
                  x-microcks-default: true
                  value: example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutRemediationConfigurationsRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - StarlingDoveService.PutRemediationConfigurations
      summary: Amazon Config Put Remediation Configurations
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=StarlingDoveService.PutRemediationConfigurations'
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  schemas:
    FailedRemediationBatches:
      type: array
      items:
        $ref: '#/components/schemas/FailedRemediationBatch'
    StringWithCharLimit256:
      type: string
      minLength: 1
      maxLength: 256
    StringWithCharLimit1024:
      type: string
      minLength: 1
      maxLength: 1024
    RemediationConfiguration:
      type: object
      required:
      - ConfigRuleName
      - TargetType
      - TargetId
      properties:
        ConfigRuleName:
          allOf:
          - $ref: '#/components/schemas/ConfigRuleName'
          - description: The name of the Config rule.
        TargetType:
          allOf:
          - $ref: '#/components/schemas/RemediationTargetType'
          - description: The type of the target. Target executes remediation. For example, SSM document.
        TargetId:
          allOf:
          - $ref: '#/components/schemas/StringWithCharLimit256'
          - description: Target ID is the name of the SSM document.
        TargetVersion:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: <p>Version of the target. For example, version of the SSM document.</p> <note> <p>If you make backward incompatible changes to the SSM document, you must call PutRemediationConfiguration API again to ensure the remediations can run.</p> </note>
        Parameters:
          allOf:
          - $ref: '#/components/schemas/RemediationParameters'
          - description: An object of the RemediationParameterValue.
        ResourceType:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'The type of a resource. '
        Automatic:
          allOf:
          - $ref: '#/components/schemas/Boolean'
          - description: The remediation is triggered automatically.
        ExecutionControls:
          allOf:
          - $ref: '#/components/schemas/ExecutionControls'
          - description: An ExecutionControls object.
        MaximumAutomaticAttempts:
          allOf:
          - $ref: '#/components/schemas/AutoRemediationAttempts'
          - description: <p>The maximum number of failed attempts for auto-remediation. If you do not select a number, the default is 5.</p> <p>For example, if you specify MaximumAutomaticAttempts as 5 with RetryAttemptSeconds as 50 seconds, Config will put a RemediationException on your behalf for the failing resource after the 5th failed attempt within 50 seconds.</p>
        RetryAttemptSeconds:
          allOf:
          - $ref: '#/components/schemas/AutoRemediationAttemptSeconds'
          - description: <p>Maximum time in seconds that Config runs auto-remediation. If you do not select a number, the default is 60 seconds. </p> <p>For example, if you specify RetryAttemptSeconds as 50 seconds and MaximumAutomaticAttempts as 5, Config will run auto-remediations 5 times within 50 seconds before throwing an exception.</p>
        Arn:
          allOf:
          - $ref: '#/components/schemas/StringWithCharLimit1024'
          - description: Amazon Resource Name (ARN) of remediation configuration.
        CreatedByService:
          allOf:
          - $ref: '#/components/schemas/StringWithCharLimit1024'
          - description: Name of the service that owns the service-linked rule, if applicable.
      description: An object that represents the details about the remediation configuration that includes the remediation action, parameters, and data to execute the action.
    RemediationConfigurations:
      type: array
      items:
        $ref: '#/components/schemas/RemediationConfiguration'
      minItems: 0
      maxItems: 25
    ResourceValue:
      type: object
      required:
      - Value
      properties:
        Value:
          allOf:
          - $ref: '#/components/schemas/ResourceValueType'
          - description: The value is a resource ID.
      description: The dynamic value of the resource.
    PutRemediationConfigurationsResponse:
      type: object
      properties:
        FailedBatches:
          allOf:
          - $ref: '#/components/schemas/FailedRemediationBatches'
          - description: Returns a list of failed remediation batch objects.
    InsufficientPermissionsException: {}
    RemediationTargetType:
      type: string
      enum:
      - SSM_DOCUMENT
    InvalidParameterValueException: {}
    Percentage:
      type: integer
      minimum: 1
      maximum: 100
    SsmControls:
      type: object
      properties:
        ConcurrentExecutionRatePercentage:
          allOf:
          - $ref: '#/components/schemas/Percentage'
          - description: 'The maximum percentage of remediation actions allowed to run in parallel on the non-compliant resources for that specific rule. You can specify a percentage, such as 10%. The default value is 10. '
        ErrorPercentage:
          allOf:
          - $ref: '#/components/schemas/Percentage'
          - description: 'The percentage of errors that are allowed before SSM stops running automations on non-compliant resources for that specific rule. You can specify a percentage of errors, for example 10%. If you do not specifiy a percentage, the default is 50%. For example, if you set the ErrorPercentage to 40% for 10 non-compliant resources, then SSM stops running the automations when the fifth error is received. '
      description: Amazon Web Services Systems Manager (SSM) specific remediation controls.
    RemediationParameterValue:
      type: object
      properties:
        ResourceValue:
          allOf:
          - $ref: '#/components/schemas/ResourceValue'
          - description: The value is dynamic and changes at run-time.
        StaticValue:
          allOf:
          - $ref: '#/components/schemas/StaticValue'
          - description: The value is static and does not change at run-time.
      description: The value is either a dynamic (resource) value or a static value. You must select either a dynamic value or a static value.
    PutRemediationConfigurationsRequest:
      type: object
      required:
      - RemediationConfigurations
      title: PutRemediationConfigurationsRequest
      properties:
        RemediationConfigurations:
          allOf:
          - $ref: '#/components/schemas/RemediationConfigurations'
          - description: A list of remediation configuration objects.
    ResourceValueType:
      type: string
      enum:
      - RESOURCE_ID
    ConfigRuleName:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 128
    RemediationParameters:
      type: object
      minProperties: 0
      maxProperties: 25
      additionalProperties:
        $ref: '#/components/schemas/RemediationParameterValue'
    StaticValue:
      type: object
      required:
      - Values
      properties:
        Values:
          allOf:
          - $ref: '#/components/schemas/StaticParameterValues'
          - description: 'A list of values. For example, the ARN of the assumed role. '
      description: The static value of the resource.
    String:
      type: string
    AutoRemediationAttempts:
      type: integer
      minimum: 1
      maximum: 25
    Boolean:
      type: boolean
    FailedRemediationBatch:
      type: object
      properties:
        FailureMessage:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: Returns a failure message. For example, the resource is already compliant.
        FailedItems:
          allOf:
          - $ref: '#/components/schemas/RemediationConfigurations'
          - description: Returns remediation configurations of the failed items.
      description: List of each of the failed remediations with specific reasons.
    StaticParameterValues:
      type: array
      items:
        $ref: '#/components/schemas/StringWithCharLimit256'
      minItems: 0
      maxItems: 25
    AutoRemediationAttemptSeconds:
      type: integer
      minimum: 1
      maximum: 2678000
    ExecutionControls:
      type: object
      properties:
        SsmControls:
          allOf:
          - $ref: '#/components/schemas/SsmControls'
          - description: A SsmControls object.
      description: The controls that Config uses for executing remediations.
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/config/
x-hasEquivalentPaths: true
