openapi: 3.0.0
info:
  version: '2014-11-12'
  x-release: v4
  title: 'AWS Config #X Amz Target=StarlingDoveService.BatchGetAggregateResourceConfig #X Amz Target=StarlingDoveService.BatchGetAggregateResourceConfig #X Amz Target=StarlingDoveService.GetResourceEvaluationSummary API'
  description: <fullname>Config</fullname> <p>Config provides a way to keep track of the configurations of all the Amazon Web Services resources associated with your Amazon Web Services account. You can use Config to get the current and historical configurations of each Amazon Web Services resource and also to get information about the relationship between the resources. An Amazon Web Services resource can be an Amazon Compute Cloud (Amazon EC2) instance, an Elastic Block Store (EBS) volume, an elastic network Interface (ENI), or a security group. For a complete list of resources currently supported by Config, see <a href="https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html#supported-resources">Supported Amazon Web Services resources</a>.</p> <p>You can access and manage Config through the Amazon Web Services Management Console, the Amazon Web Services Command Line Interface (Amazon Web Services CLI), the Config API, or the Amazon Web Services SDKs for Config. This reference guide contains documentation for the Config API and the Amazon Web Services CLI commands that you can use to manage Config. The Config API uses the Signature Version 4 protocol for signing requests. For more information about how to sign a request with this protocol, see <a href="https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html">Signature Version 4 Signing Process</a>. For detailed information about Config features and their associated actions or commands, as well as how to work with Amazon Web Services Management Console, see <a href="https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html">What Is Config</a> in the <i>Config Developer Guide</i>.</p>
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: config
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/config-2014-11-12.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://config.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Config Service multi-region endpoint
- url: https://config.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Config Service multi-region endpoint
- url: http://config.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Config Service endpoint for China (Beijing) and China (Ningxia)
- url: https://config.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Config Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=StarlingDoveService.GetResourceEvaluationSummary'
paths:
  /#X-Amz-Target=StarlingDoveService.GetResourceEvaluationSummary:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetResourceEvaluationSummary
      description: <p>Returns a summary of resource evaluation for the specified resource evaluation ID from the proactive rules that were run. The results indicate which evaluation context was used to evaluate the rules, which resource details were evaluated, the evaluation mode that was run, and whether the resource details comply with the configuration of the proactive rules. </p> <note> <p>To see additional information about the evaluation result, such as which rule flagged a resource as NON_COMPLIANT, use the <a href="https://docs.aws.amazon.com/config/latest/APIReference/API_GetComplianceDetailsByResource.html">GetComplianceDetailsByResource</a> API. For more information, see the <a href="https://docs.aws.amazon.com/config/latest/APIReference/API_GetResourceEvaluationSummary.html#API_GetResourceEvaluationSummary_Examples">Examples</a> section.</p> </note>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetResourceEvaluationSummaryResponse'
              examples:
                GetResourceEvaluationSummary200Example:
                  summary: Default GetResourceEvaluationSummary 200
                  x-microcks-default: true
                  value:
                    ResourceEvaluationId: example
                    EvaluationMode: example
                    EvaluationStatus: example
                    EvaluationStartTimestamp: example
                    Compliance: example
                    EvaluationContext: example
                    ResourceDetails: example
        '480':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                GetResourceEvaluationSummary480Example:
                  summary: Default GetResourceEvaluationSummary 480
                  x-microcks-default: true
                  value: example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetResourceEvaluationSummaryRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - StarlingDoveService.GetResourceEvaluationSummary
      summary: Amazon Config Get Resource Evaluation Summary
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=StarlingDoveService.GetResourceEvaluationSummary'
components:
  schemas:
    ResourceEvaluationStatus:
      type: string
      enum:
      - IN_PROGRESS
      - FAILED
      - SUCCEEDED
    BaseResourceId:
      type: string
      minLength: 1
      maxLength: 768
    StringWithCharLimit256:
      type: string
      minLength: 1
      maxLength: 256
    ResourceConfiguration:
      type: string
      minLength: 1
      maxLength: 51200
    StringWithCharLimit1024:
      type: string
      minLength: 1
      maxLength: 1024
    ResourceConfigurationSchemaType:
      type: string
      enum:
      - CFN_RESOURCE_SCHEMA
    Date:
      type: string
      format: date-time
    GetResourceEvaluationSummaryRequest:
      type: object
      required:
      - ResourceEvaluationId
      title: GetResourceEvaluationSummaryRequest
      properties:
        ResourceEvaluationId:
          allOf:
          - $ref: '#/components/schemas/ResourceEvaluationId'
          - description: The unique <code>ResourceEvaluationId</code> of Amazon Web Services resource execution for which you want to retrieve the evaluation summary.
    ResourceDetails:
      type: object
      required:
      - ResourceId
      - ResourceType
      - ResourceConfiguration
      properties:
        ResourceId:
          allOf:
          - $ref: '#/components/schemas/BaseResourceId'
          - description: A unique resource ID for an evaluation.
        ResourceType:
          allOf:
          - $ref: '#/components/schemas/StringWithCharLimit256'
          - description: The type of resource being evaluated.
        ResourceConfiguration:
          allOf:
          - $ref: '#/components/schemas/ResourceConfiguration'
          - description: The resource definition to be evaluated as per the resource configuration schema type.
        ResourceConfigurationSchemaType:
          allOf:
          - $ref: '#/components/schemas/ResourceConfigurationSchemaType'
          - description: '<p>The schema type of the resource configuration.</p> <note> <p>You can find the <a href="https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-schema.html">Resource type schema</a>, or <code>CFN_RESOURCE_SCHEMA</code>, in "<i>Amazon Web Services public extensions</i>" within the CloudFormation registry or with the following CLI commmand: <code>aws cloudformation describe-type --type-name "AWS::S3::Bucket" --type RESOURCE</code>.</p> <p>For more information, see <a href="https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/registry.html#registry-view">Managing extensions through the CloudFormation registry</a> and <a href="https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html">Amazon Web Services resource and property types reference</a> in the CloudFormation User Guide.</p> </note>'
      description: Returns information about the resource being evaluated.
    EvaluationStatus:
      type: object
      required:
      - Status
      properties:
        Status:
          allOf:
          - $ref: '#/components/schemas/ResourceEvaluationStatus'
          - description: 'The status of an execution. The valid values are In_Progress, Succeeded or Failed. '
        FailureReason:
          allOf:
          - $ref: '#/components/schemas/StringWithCharLimit1024'
          - description: An explanation for failed execution status.
      description: Returns status details of an evaluation.
    ComplianceType:
      type: string
      enum:
      - COMPLIANT
      - NON_COMPLIANT
      - NOT_APPLICABLE
      - INSUFFICIENT_DATA
    EvaluationContextIdentifier:
      type: string
      minLength: 1
      maxLength: 128
    ResourceEvaluationId:
      type: string
      minLength: 1
      maxLength: 128
    GetResourceEvaluationSummaryResponse:
      type: object
      properties:
        ResourceEvaluationId:
          allOf:
          - $ref: '#/components/schemas/ResourceEvaluationId'
          - description: The unique <code>ResourceEvaluationId</code> of Amazon Web Services resource execution for which you want to retrieve the evaluation summary.
        EvaluationMode:
          allOf:
          - $ref: '#/components/schemas/EvaluationMode'
          - description: Lists results of the mode that you requested to retrieve the resource evaluation summary. The valid values are Detective or Proactive.
        EvaluationStatus:
          allOf:
          - $ref: '#/components/schemas/EvaluationStatus'
          - description: Returns an <code>EvaluationStatus</code> object.
        EvaluationStartTimestamp:
          allOf:
          - $ref: '#/components/schemas/Date'
          - description: The start timestamp when Config rule starts evaluating compliance for the provided resource details.
        Compliance:
          allOf:
          - $ref: '#/components/schemas/ComplianceType'
          - description: The compliance status of the resource evaluation summary.
        EvaluationContext:
          allOf:
          - $ref: '#/components/schemas/EvaluationContext'
          - description: Returns an <code>EvaluationContext</code> object.
        ResourceDetails:
          allOf:
          - $ref: '#/components/schemas/ResourceDetails'
          - description: Returns a <code>ResourceDetails</code> object.
    EvaluationContext:
      type: object
      properties:
        EvaluationContextIdentifier:
          allOf:
          - $ref: '#/components/schemas/EvaluationContextIdentifier'
          - description: A unique EvaluationContextIdentifier ID for an EvaluationContext.
      description: Use EvaluationContext to group independently initiated proactive resource evaluations. For example, CFN Stack. If you want to check just a resource definition, you do not need to provide evaluation context.
    EvaluationMode:
      type: string
      enum:
      - DETECTIVE
      - PROACTIVE
    ResourceNotFoundException: {}
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/config/
x-hasEquivalentPaths: true
