openapi: 3.0.0
info:
  version: '2014-11-12'
  x-release: v4
  title: 'AWS Config #X Amz Target=StarlingDoveService.BatchGetAggregateResourceConfig #X Amz Target=StarlingDoveService.BatchGetAggregateResourceConfig #X Amz Target=StarlingDoveService.PutConfigurationAggregator API'
  description: <fullname>Config</fullname> <p>Config provides a way to keep track of the configurations of all the Amazon Web Services resources associated with your Amazon Web Services account. You can use Config to get the current and historical configurations of each Amazon Web Services resource and also to get information about the relationship between the resources. An Amazon Web Services resource can be an Amazon Compute Cloud (Amazon EC2) instance, an Elastic Block Store (EBS) volume, an elastic network Interface (ENI), or a security group. For a complete list of resources currently supported by Config, see <a href="https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html#supported-resources">Supported Amazon Web Services resources</a>.</p> <p>You can access and manage Config through the Amazon Web Services Management Console, the Amazon Web Services Command Line Interface (Amazon Web Services CLI), the Config API, or the Amazon Web Services SDKs for Config. This reference guide contains documentation for the Config API and the Amazon Web Services CLI commands that you can use to manage Config. The Config API uses the Signature Version 4 protocol for signing requests. For more information about how to sign a request with this protocol, see <a href="https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html">Signature Version 4 Signing Process</a>. For detailed information about Config features and their associated actions or commands, as well as how to work with Amazon Web Services Management Console, see <a href="https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html">What Is Config</a> in the <i>Config Developer Guide</i>.</p>
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: config
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/config-2014-11-12.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://config.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Config Service multi-region endpoint
- url: https://config.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Config Service multi-region endpoint
- url: http://config.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Config Service endpoint for China (Beijing) and China (Ningxia)
- url: https://config.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Config Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=StarlingDoveService.PutConfigurationAggregator'
paths:
  /#X-Amz-Target=StarlingDoveService.PutConfigurationAggregator:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: PutConfigurationAggregator
      description: <p>Creates and updates the configuration aggregator with the selected source accounts and regions. The source account can be individual account(s) or an organization.</p> <p> <code>accountIds</code> that are passed will be replaced with existing accounts. If you want to add additional accounts into the aggregator, call <code>DescribeConfigurationAggregators</code> to get the previous accounts and then append new ones.</p> <note> <p>Config should be enabled in source accounts and regions you want to aggregate.</p> <p>If your source type is an organization, you must be signed in to the management account or a registered delegated administrator and all the features must be enabled in your organization. If the caller is a management account, Config calls <code>EnableAwsServiceAccess</code> API to enable integration between Config and Organizations. If the caller is a registered delegated administrator, Config calls <code>ListDelegatedAdministrators</code> API to verify whether the caller is a valid delegated administrator.</p> <p>To register a delegated administrator, see <a href="https://docs.aws.amazon.com/config/latest/developerguide/set-up-aggregator-cli.html#register-a-delegated-administrator-cli">Register a Delegated Administrator</a> in the <i>Config developer guide</i>. </p> </note> <note> <p> <code>PutConfigurationAggregator</code> is an idempotent API. Subsequent requests won’t create a duplicate resource if one was already created. If a following request has different <code>tags</code> values, Config will ignore these differences and treat it as an idempotent request of the previous. In this case, <code>tags</code> will not be updated, even if they are different.</p> </note>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutConfigurationAggregatorResponse'
              examples:
                PutConfigurationAggregator200Example:
                  summary: Default PutConfigurationAggregator 200
                  x-microcks-default: true
                  value:
                    ConfigurationAggregator: example
        '480':
          description: InvalidParameterValueException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterValueException'
              examples:
                PutConfigurationAggregator480Example:
                  summary: Default PutConfigurationAggregator 480
                  x-microcks-default: true
                  value: example
        '481':
          description: LimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LimitExceededException'
              examples:
                PutConfigurationAggregator481Example:
                  summary: Default PutConfigurationAggregator 481
                  x-microcks-default: true
                  value: example
        '482':
          description: InvalidRoleException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRoleException'
              examples:
                PutConfigurationAggregator482Example:
                  summary: Default PutConfigurationAggregator 482
                  x-microcks-default: true
                  value: example
        '483':
          description: OrganizationAccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationAccessDeniedException'
              examples:
                PutConfigurationAggregator483Example:
                  summary: Default PutConfigurationAggregator 483
                  x-microcks-default: true
                  value: example
        '484':
          description: NoAvailableOrganizationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoAvailableOrganizationException'
              examples:
                PutConfigurationAggregator484Example:
                  summary: Default PutConfigurationAggregator 484
                  x-microcks-default: true
                  value: example
        '485':
          description: OrganizationAllFeaturesNotEnabledException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationAllFeaturesNotEnabledException'
              examples:
                PutConfigurationAggregator485Example:
                  summary: Default PutConfigurationAggregator 485
                  x-microcks-default: true
                  value: example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutConfigurationAggregatorRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - StarlingDoveService.PutConfigurationAggregator
      summary: Amazon Config Put Configuration Aggregator
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=StarlingDoveService.PutConfigurationAggregator'
components:
  schemas:
    Tag:
      type: object
      properties:
        Key:
          allOf:
          - $ref: '#/components/schemas/TagKey'
          - description: One part of a key-value pair that make up a tag. A key is a general label that acts like a category for more specific tag values.
        Value:
          allOf:
          - $ref: '#/components/schemas/TagValue'
          - description: The optional part of a key-value pair that make up a tag. A value acts as a descriptor within a tag category (key).
      description: The tags for the resource. The metadata that you apply to a resource to help you categorize and organize them. Each tag consists of a key and an optional value, both of which you define. Tag keys can have a maximum character length of 128 characters, and tag values can have a maximum length of 256 characters.
    StringWithCharLimit256:
      type: string
      minLength: 1
      maxLength: 256
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TagsList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
      minItems: 0
      maxItems: 50
    AccountAggregationSourceAccountList:
      type: array
      items:
        $ref: '#/components/schemas/AccountId'
      minItems: 1
    ConfigurationAggregator:
      type: object
      properties:
        ConfigurationAggregatorName:
          allOf:
          - $ref: '#/components/schemas/ConfigurationAggregatorName'
          - description: The name of the aggregator.
        ConfigurationAggregatorArn:
          allOf:
          - $ref: '#/components/schemas/ConfigurationAggregatorArn'
          - description: The Amazon Resource Name (ARN) of the aggregator.
        AccountAggregationSources:
          allOf:
          - $ref: '#/components/schemas/AccountAggregationSourceList'
          - description: Provides a list of source accounts and regions to be aggregated.
        OrganizationAggregationSource:
          allOf:
          - $ref: '#/components/schemas/OrganizationAggregationSource'
          - description: Provides an organization and list of regions to be aggregated.
        CreationTime:
          allOf:
          - $ref: '#/components/schemas/Date'
          - description: The time stamp when the configuration aggregator was created.
        LastUpdatedTime:
          allOf:
          - $ref: '#/components/schemas/Date'
          - description: The time of the last update.
        CreatedBy:
          allOf:
          - $ref: '#/components/schemas/StringWithCharLimit256'
          - description: Amazon Web Services service that created the configuration aggregator.
      description: 'The details about the configuration aggregator, including information about source accounts, regions, and metadata of the aggregator. '
    Date:
      type: string
      format: date-time
    ConfigurationAggregatorArn:
      type: string
      pattern: arn:aws[a-z\-]*:config:[a-z\-\d]+:\d+:config-aggregator/config-aggregator-[a-z\d]+
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    LimitExceededException: {}
    InvalidRoleException: {}
    PutConfigurationAggregatorResponse:
      type: object
      properties:
        ConfigurationAggregator:
          allOf:
          - $ref: '#/components/schemas/ConfigurationAggregator'
          - description: Returns a ConfigurationAggregator object.
    PutConfigurationAggregatorRequest:
      type: object
      required:
      - ConfigurationAggregatorName
      title: PutConfigurationAggregatorRequest
      properties:
        ConfigurationAggregatorName:
          allOf:
          - $ref: '#/components/schemas/ConfigurationAggregatorName'
          - description: The name of the configuration aggregator.
        AccountAggregationSources:
          allOf:
          - $ref: '#/components/schemas/AccountAggregationSourceList'
          - description: 'A list of AccountAggregationSource object. '
        OrganizationAggregationSource:
          allOf:
          - $ref: '#/components/schemas/OrganizationAggregationSource'
          - description: An OrganizationAggregationSource object.
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagsList'
          - description: An array of tag object.
    InvalidParameterValueException: {}
    AccountAggregationSource:
      type: object
      required:
      - AccountIds
      properties:
        AccountIds:
          allOf:
          - $ref: '#/components/schemas/AccountAggregationSourceAccountList'
          - description: 'The 12-digit account ID of the account being aggregated. '
        AllAwsRegions:
          allOf:
          - $ref: '#/components/schemas/Boolean'
          - description: If true, aggregate existing Config regions and future regions.
        AwsRegions:
          allOf:
          - $ref: '#/components/schemas/AggregatorRegionList'
          - description: The source regions being aggregated.
      description: A collection of accounts and regions.
    OrganizationAllFeaturesNotEnabledException: {}
    AggregatorRegionList:
      type: array
      items:
        $ref: '#/components/schemas/String'
      minItems: 1
    ConfigurationAggregatorName:
      type: string
      pattern: '[\w\-]+'
      minLength: 1
      maxLength: 256
    String:
      type: string
    NoAvailableOrganizationException: {}
    Boolean:
      type: boolean
    AccountAggregationSourceList:
      type: array
      items:
        $ref: '#/components/schemas/AccountAggregationSource'
      minItems: 0
      maxItems: 1
    AccountId:
      type: string
      pattern: \d{12}
    OrganizationAggregationSource:
      type: object
      required:
      - RoleArn
      properties:
        RoleArn:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: ARN of the IAM role used to retrieve Amazon Web Services Organization details associated with the aggregator account.
        AwsRegions:
          allOf:
          - $ref: '#/components/schemas/AggregatorRegionList'
          - description: The source regions being aggregated.
        AllAwsRegions:
          allOf:
          - $ref: '#/components/schemas/Boolean'
          - description: If true, aggregate existing Config regions and future regions.
      description: This object contains regions to set up the aggregator and an IAM role to retrieve organization details.
    OrganizationAccessDeniedException: {}
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/config/
x-hasEquivalentPaths: true
